apiVersion: apis.kcp.io/v1alpha2
kind: APIExport
metadata:
  creationTimestamp: null
  name: gateway.platform-mesh.io
spec:
  permissionClaims:
  - resource: namespaces
    verbs:
    - '*'
  resources:
  - group: gateway.platform-mesh.io
    name: clusteraccesses
    schema: v260127-84a8fb4.clusteraccesses.gateway.platform-mesh.io
    storage:
      crd: {}
status: {}
