name: ci
on: [push]

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-golang-app.yml@main
    secrets: inherit
    with:
      useTask: true
      useLocalCoverageConfig: true
      imageTagName: ghcr.io/openmfp/crd-gql-gateway
      coverageThreasholdFile: 0
      coverageThresholdPackage: 0
      coverageThreasholdTotal: 0

