name: ci
on: 
  push:
    branches:
      - main
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  pipe:
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: true
    uses: openmfp/gha/.github/workflows/pipeline-golang-app.yml@main
    secrets: inherit
    with:
      useTask: true
      useLocalCoverageConfig: true
      imageTagName: ghcr.io/openmfp/kubernetes-graphql-gateway
      coverageThreasholdFile: 49
      coverageThresholdPackage: 65
      coverageThreasholdTotal: 62


